language: python
python:
  - "3.6"
  - "nightly" # currently points to 3.7-dev
install:
    - "pip install -r requirements-test.txt"
script:
    PYTHONPATH=. py.test --cov
after_success:
    coveralls